### ISSUE TITLE
Add ability to read config values from the environemnt for Makai.

### ISSUE THREAD

**Issue by anthonyjchriste** [openpowerquality/opq#210]
Please do work for this task in a branch called issue-210.

The proper way to do networking in docker compose is to pass around env vars. This was explained by David.

"""
So, each docker container is basically its own computer, with its own network. So, mauka right now is connecting to mongodb with the `mongodb://localhost:27017` url string, but actually this doesn’t work, because the Mongo service now lives in its own container (its own ‘computer’ with its own network). `localhost` in Mauka’s container is different than `localhost` in the Mongo container. Each container has its own loopback interface. Makes sense, right?

So Docker-Compose makes life easier for us by providing us a hostname for each service we define in docker-compose.yml. This hostname points to the actual ip address of the docker container that docker manages for us.

So, now we can use the following mongo url to connect to the mongo container `mongodb://mongo:27017`, where `mongo` is the service name we defined in docker-compose.yml for the mongodb service.

So we need Mauka (and every other service) to receive that url string somehow in order to connect to the Mongo docker container. We can either hardcode that value directly into your code, or, the real solution, have each service accept environment variables that allow us to set these values.
"""

Determine which URLs can be used an env vars. Edit Makai to read from environment when signaled from config. This includes ZMQ stuff, so may want to come up with common env vars between Mauka and Makai.

**Comment by aghalarp** [comment]
@anthonyjchriste's work setting up env vars for Mauka allowed me experiment and gain a much better understanding of Docker networking. To narrow this down a bit for you, there are three general cases to be concerned about:

**1. Client connection to another container:**
Recall that each docker container has its own isolated network. We will need to be able to set an environment variable for any client-side connections from Makai to a server that lives within **another** container.
Ie. If Makai currently connects to a server listening in the Mauka container, the connecting string `tcp://localhost:1234` wouldn’t work, because that server is listening on Mauka’s network now. With Docker Compose, we essentially turn this into `tcp://mauka:1234`, provided that Makai allows us to set an environment variable for this networking url.

**2. Container hosting a server for other containers to connect to:**
If the Makai container is hosting a server and expects connections from other containers, we need to expose the port that the server is listening on. Assuming that this server is listening on 0.0.0.0 or *, we only require knowledge of the port number so that we can expose it to other containers. In fact, if you do not wish for the port number to be configurable, you don’t need to provide an env var for this. 

**3. Container hosting a server for the outside world to connect to:**
Lastly, if the container is hosting a server and expecting connections from the outside world (as opposed to just another container), we need to expose and map the port directly to the host machine. The server should also be listening on 0.0.0.0 or * here as well. Again, if you do not want this port to be configurable, you do not need to provide an env var for it. Just let us know which ports need to be exposed to the outside world. I imagine one case for this is for the port(s) that Makai listens on for OPQ box data.

There’s no immediate rush to implement this, as I should be able to hook up our current docker compose network with Makai even if it is not yet dockerized. But this relies on some trickery and is not an ideal long term solution, especially if we plan on moving off Emilia and onto AWS or some other cloud service.

**Comment by philipmjohnson** [comment]
I wonder if these insights should ultimately make it into our Docker Docs as "background info" or something?
