### ISSUE TITLE
Fix broken Edit buttons in View Admin management pages

### ISSUE THREAD

**Issue by philipmjohnson** [openpowerquality/opq#234]
Please do work for this task in a branch called issue-234.

Seems like admin entities (users, opq boxes, regions, locations) cannot be edited because the edit button does not work.  Fix this.

- [x] Location editing fixed
- [x] OPQ Box editing fixed
- [x] User editing fixed
- [x] Region editing fixed

**Comment by aghalarp** [comment]
I briefly investigated this a couple days ago. Not sure if this is of any help, but it seems like the root of this problem is that edit urls are being passed as ObjectID objects, rather than their string representations. I believe you can use the `ObjectID.toHexString()` function to just grab the _id as a string, and use that in all the edit urls.

Subsequently, if you need to query Mongo by an actual ObjectID object, you can just just create one with `new Mongo.ObjectID()`. In the case of these edit buttons, we are receiving the _id from the url, so this will probably look like `new Mongo.ObjectID(match.params._id)`.

**Comment by philipmjohnson** [comment]
Fixed locations and Users.  OPQ Boxes was actually working from the start. Region management is not even implemented so nothing to "fix".
