### ISSUE TITLE
Rename Box ID key in events collection

### ISSUE THREAD

**Issue by aghalarp** [openpowerquality/opq#8]
Please do work for this task in a branch called issue-8.

The data collection has a key named "Box ID" (with a space). We should rename this to boxId. As a convention, let's append any key that holds a Mongo id value with an "_id", and any key that holds a non-mongo id value with just "Id" using camelcase.

**Comment by philipmjohnson** [comment]
I agree that you don't want spaces in field names. 

I do not recommend that you distinguish between mongo IDs and other IDs using the case of the letter "I".  That is a recipe for endless mistakes!

Instead, if there are multiple kinds of IDs, make the naming scheme obvious by adding the system name. 

So, instead of "Box ID", use boxMongoID or box_mongo_id or something similar.

**Comment by sergey-negrashov** [comment]
As of 9531e6aac783874ddcc659ac127da22f542bb688 Box ID is now mongo_box_id.

**Comment by aghalarp** [comment]
The "Box ID" field in question here is a non-mongo id (just an integer value we assign to our devices). Sorry for the confusion in my original post - I was just taking the opportunity to clarify naming conventions between mongo id fields and non-mongo id fields.

So let's just rename this to "box_id", indicating a non-mongo id field.

And to finalize our naming conventions:
Non-mongo id --> append field name with "_id"
Mongo id --> append field name with "_mongo_id"

**Comment by aghalarp** [comment]
There is also another minor typo in the "events" collection.
"boxes_recieved" --> "boxes_received"

**Comment by sergey-negrashov** [comment]
Fixed in commit 9531e6a.
